# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Builder
FROM node:lts-alpine AS builder
WORKDIR /app
COPY MssqlMcp/Node/package.json MssqlMcp/Node/package-lock.json ./
COPY MssqlMcp/Node/tsconfig.json ./
COPY MssqlMcp/Node/src ./src
# Remove HTTP server file to avoid TS errors
RUN rm src/http-server.ts || true
RUN npm install && npm run build

# Runtime
FROM node:lts-alpine
WORKDIR /app
# Copy dist and package files
COPY --from=builder /app/dist ./dist
COPY MssqlMcp/Node/package.json MssqlMcp/Node/package-lock.json ./
# Install production deps without scripts
RUN npm install --production --ignore-scripts
CMD ["node", "dist/index.js"]
